# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kq0xCGpHzFia2s_qI1shJ14h3jazuXg_
"""

from sklearn.datasets import load_breast_cancer
breast_cancer_data = load_breast_cancer()
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

breast_cancer_data=load_breast_cancer()

#Inspect data
breast_cancer_data.data[0]

#Inspect data
breast_cancer_data.feature_names

#Inspect tags
breast_cancer_data.target

#Inspect tags
breast_cancer_data.target_names

#Splitting the data into Training and Validation Sets
training_data, validation_data, training_labels, validation_labels = train_test_split(breast_cancer_data.data, breast_cancer_data.target, test_size = 0.2, random_state = 100)

#Crosschecking data split
print(len(training_data))
print(len(training_labels))

#Running the classifier and graphing out accuracies of k to find out suitable value of 'k'
accuracies=[]
for k in range(1, 101):
  classifier = KNeighborsClassifier(k)
  classifier.fit(training_data, training_labels)
  accuracies.append(classifier.score(validation_data, validation_labels))

#Visualization
#The x-axis would range from 1-100 showing the values of 'k' that we tested
#The y-axis shows the validation accuracies

k_list = range(1,101)
plt.plot(k_list, accuracies)
plt.xlabel("k")
plt.ylabel("Validation Accuracy")
plt.title("Breast Cancer Classifier Accuracy")
plt.show()